spring:
  application:
    name: number-guessing-game
  profiles:
    active: console

game:
  statistics:
    directory: structural-patterns/adapter-pattern/src/main/resources/stats
  range:
    min: 1
    max: 3
