spring:
  application:
    name: number-guessing-game
  profiles:
    active: console

game:
  statistics:
    file-path: structural-patterns/adapter-pattern/src/main/resources/stats/stats.csv
  range:
    min: 1
    max: 3
